#!/usr/bin/env python3
"""Regenerate reference/banned-persons.yml and reference/modern-slavery.yml.

Two integrity registers that Australia publishes openly and nobody joins to procurement.

  BannedPerson  <- ASIC Banned & Disqualified persons (data.gov.au, CC BY 3.0 AU, monthly).
                   Filtered to bans IN FORCE: a ban that expired in 1999 is history, not a risk
                   signal, and carrying all 7,202 rows would bury the ~1,950 that matter.
  ModernSlaveryStatement <- Modern Slavery Statements Register (per-year CSV).
                   Carries ABN/ACN/ARBN as first-class columns AND `ReportingEntities` /
                   `IncludedEntities` listing every covered ABN inline — corporate group
                   structure with no entity resolution required.

WHY THESE ARE REFERENCE DATA AND GRANTS WERE NOT: both are periodic REGISTER SNAPSHOTS with no
API — small, slow-moving catalogues of the kind reference/ exists for. Grants are a live feed of
thousands of records with a publication cadence; that is a producer's job, and seeding it was the
wrong call.

TWO LICENCE NOTES.
 - ASIC data here is taken from ASIC's OWN data.gov.au releases (CC BY 3.0 AU). Never scrape ASIC
   Connect or published notices: ASIC requires written permission to reproduce register content
   outside its named CC-BY classes.
 - The Modern Slavery Register domain carries NO licence statement and its /terms-of-use/ 404s.
   AGD's site-wide CC BY 4.0 is a different domain and carves out third-party content, which
   lodged statements plainly are. This takes METADATA ONLY and deep-links each PDF. Get AGD's
   written confirmation before any commercial surface.

Run from the realm root:  python3 scripts/build-integrity-reference.py
"""
import csv
import datetime
import io
import json
import re
import urllib.request

UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}
ASIC_PKG = "https://data.gov.au/data/api/3/action/package_show?id=asic-banned-disqualified-per"
MS_RESOURCES = "https://modernslaveryregister.gov.au/resources/"
MS_YEARS = ("2026", "2025")


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=300).read()


def yq(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def digits(s):
    return re.sub(r"\D", "", s or "")


def build_banned():
    pkg = json.loads(fetch(ASIC_PKG))["result"]
    csvs = [r for r in pkg["resources"] if (r.get("format") or "").upper() == "CSV"]
    latest = sorted(csvs, key=lambda r: r.get("name", ""))[-1]
    rows = list(csv.DictReader(io.StringIO(fetch(latest["url"]).decode("utf-8-sig"))))
    today = datetime.date.today()

    def parse(s):
        try:
            return datetime.datetime.strptime((s or "").strip(), "%d/%m/%Y").date()
        except ValueError:
            return None

    kept = []
    for r in rows:
        end = parse(r.get("BD_PER_END_DT"))
        if end is not None and end < today:
            continue  # expired: history, not a live risk signal
        kept.append({
            "banKey": f'{r["BD_PER_NAME"]}|{r.get("BD_PER_DOC_NUM","")}'.strip("|"),
            "name": r["BD_PER_NAME"].strip(),
            "banType": (r.get("BD_PER_TYPE") or "").strip(),
            "documentNumber": (r.get("BD_PER_DOC_NUM") or "").strip(),
            "startDate": (r.get("BD_PER_START_DT") or "").strip(),
            "endDate": (r.get("BD_PER_END_DT") or "").strip(),
            "locality": (r.get("BD_PER_ADD_LOCAL") or "").strip(),
            "state": (r.get("BD_PER_ADD_STATE") or "").strip(),
            "postcode": (r.get("BD_PER_ADD_PCODE") or "").strip(),
        })

    with open("reference/banned-persons.yml", "w") as f:
        f.write("# GENERATED by scripts/build-integrity-reference.py — do not hand-edit.\n")
        f.write(f"# Source: ASIC Banned & Disqualified persons via {latest.get('name','data.gov.au')} (CC BY 3.0 AU).\n")
        f.write(f"# Filtered to bans IN FORCE as at {today.isoformat()}: {len(kept)} of {len(rows)} rows.\n")
        f.write("#\n")
        f.write("# MATCHING IS BY NAME AND LOCALITY ONLY — the register publishes no date of birth and\n")
        f.write("# no ABN. A name match is a SCREENING PROMPT for a human, never a determination that a\n")
        f.write("# particular individual is banned, and no surface may present it as one.\n\n")
        for k in kept:
            data = ", ".join(f"{kk}: {yq(vv)}" for kk, vv in k.items() if vv)
            f.write(f"- type: BannedPerson\n  data: {{ {data} }}\n")
    print(f"reference/banned-persons.yml: {len(kept)} in-force bans (of {len(rows)})")


def build_modern_slavery():
    page = fetch(MS_RESOURCES).decode("utf-8", "ignore")
    seen, out = set(), []
    for year in MS_YEARS:
        m = re.search(r'href="(/resources/statement-information-%s_[^"]+\.csv)"' % year, page)
        if not m:
            print(f"  WARNING no CSV link for {year}")
            continue
        rows = list(csv.DictReader(io.StringIO(
            fetch("https://modernslaveryregister.gov.au" + m.group(1)).decode("utf-8-sig"))))
        for r in rows:
            abn = digits(r.get("ABN"))
            idx = (r.get("IDX") or "").strip()
            key = idx or abn
            if not key or key in seen:
                continue
            seen.add(key)
            # Every ABN named in the statement — the reporting entity plus every entity it covers.
            # This is the corporate-group structure, free, with no entity resolution needed.
            group = sorted({d for d in
                            (digits(x) for x in re.findall(r"\(([\d\s]{11,20})\)",
                                                           (r.get("ReportingEntities") or "") + " " +
                                                           (r.get("IncludedEntities") or "")))
                            if len(d) == 11})
            out.append({
                "statementId": key,
                "year": year,
                "abn": abn,
                "acn": digits(r.get("ACN")),
                "reportingEntities": (r.get("ReportingEntities") or "").replace("\n", "; ").strip()[:180],
                "coveredAbns": group,
                "annualRevenue": (r.get("AnnualRevenue") or "").strip(),
                "industrySectors": (r.get("IndustrySectors") or "").replace("\n", "; ").strip()[:90],
                "periodEnd": (r.get("PeriodEnd") or "").strip(),
                "link": (r.get("Link") or "").strip(),
            })

    # Keep every file well under SnakeYAML's ~3MB document limit: over it, the realm loader drops
    # the WHOLE file and records one terse problem, so the data vanishes silently.
    import glob as _glob, os as _os
    for old in _glob.glob("reference/modern-slavery-*.yml"):
        _os.remove(old)
    for yr in MS_YEARS:
      part = [x for x in out if x["year"] == yr]
      if not part:
          continue
      with open(f"reference/modern-slavery-{yr}.yml", "w") as f:
        f.write("# GENERATED by scripts/build-integrity-reference.py — do not hand-edit.\n")
        f.write("# Source: Modern Slavery Statements Register, per-year CSV. METADATA ONLY — each\n")
        f.write("# statement is deep-linked, never reproduced (see the licence note in the script).\n")
        f.write("#\n")
        f.write("# `coveredAbns` is every ABN named in the statement's reporting/included entities:\n")
        f.write("# corporate GROUP STRUCTURE, published by the entities themselves, with no entity\n")
        f.write("# resolution required. A supplier appearing in another company's group is a\n")
        f.write("# disclosed relationship — never an inference.\n")
        f.write("#\n")
        f.write("# Lodging a statement is COMPLIANCE, not wrongdoing. Absence is not non-compliance\n")
        f.write("# either: the obligation applies only above a A$100m consolidated-revenue threshold.\n\n")
        for s in part:
            fields = []
            for kk, vv in s.items():
                if isinstance(vv, list):
                    if vv:
                        fields.append(f"{kk}: [" + ", ".join(yq(v) for v in vv) + "]")
                elif vv:
                    fields.append(f"{kk}: {yq(vv)}")
            f.write(f"- type: ModernSlaveryStatement\n  data: {{ {', '.join(fields)} }}\n")
    grouped = sum(1 for s in out if len(s["coveredAbns"]) > 1)
    print(f"reference/modern-slavery.yml: {len(out)} statements, {grouped} naming a multi-entity group")


if __name__ == "__main__":
    build_banned()
    build_modern_slavery()
