#!/usr/bin/env python3
"""Regenerate reference/agencies.yml and reference/procurement-grounds.yml. Do not hand-edit those.

The entity spine this realm seeds into the KG on world load (idempotent identity-MERGE):

  Portfolio          <- AGOR (data.gov.au, CC BY 3.0 AU) — the ~17 Commonwealth portfolios
  Agency             <- AGOR primary bodies, with ABN, body type, staffing and appropriations
  ProcurementGround  <- HARVESTED FROM THE LIVE FEED, not transcribed from the rules: every
                        distinct (limitedTenderReasonCode, limitedTenderReason) and
                        (exemptionCode, exemption) pair AusTender actually published in the
                        scanned window, with the register's verbatim text.

Why harvest rather than transcribe: the Commonwealth Procurement Rules are a document we would
be paraphrasing from memory, and a paraphrased rule presented as a citation is exactly the
failure this realm exists to avoid. The register states its own grounds; we seed what it says.

AGENCY NAME ALIASES: AusTender and AGOR spell some entities differently (AusTender publishes
'Austrade' where AGOR has the legal title; it also publishes program-level names like
'Department of Foreign Affairs and Trade - Australian Aid Program' that AGOR has no row for).
That drift cannot be derived by a rule — same problem realm-nsw-property has with council names
— so ALIASES is an explicit, reviewable map here. Unmatched AusTender agency names are written
into the file as a commented gap list rather than silently dropped.

Run from the realm root:  python3 scripts/build-reference-data.py
"""
import collections
import csv
import io
import json
import time
import urllib.request

AGOR_PKG = "https://data.gov.au/data/api/3/action/package_show?id=australian-government-organisations-register"
OCDS = "https://api.tenders.gov.au/ocds/findByDates/contractPublished/{f}T00:00:00Z/{t}T00:00:00Z"
UA = {"User-Agent": "Mozilla/5.0 (realm-gov-au build-reference-data)", "Accept": "application/json"}

# AusTender spelling -> AGOR Title. Extend as new drift is observed; the build prints unmatched names.
ALIASES = {
    "Austrade": "Australian Trade and Investment Commission (Austrade)",
    "Department of Foreign Affairs and Trade - Australian Aid Program": "Department of Foreign Affairs and Trade",
}

# Days to scan for procurement grounds. More days = more of the code catalogue observed.
SCAN_DAYS = [("2026-07-20", "2026-07-21"), ("2026-07-22", "2026-07-23"), ("2026-07-24", "2026-07-25"),
             ("2026-07-27", "2026-07-28"), ("2026-07-29", "2026-07-30")]


def fetch(url, raw=False):
    data = urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120).read()
    return data if raw else json.loads(data)


def yq(s):
    """Quote a scalar for YAML: always double-quote and escape, so commas/colons/quotes are safe."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def latest_agor_rows():
    pkg = fetch(AGOR_PKG)["result"]
    csvs = sorted([r for r in pkg["resources"] if (r.get("format") or "").upper() == "CSV"],
                  key=lambda r: r.get("name", ""))
    blob = fetch(csvs[-1]["url"], raw=True).decode("utf-8-sig")
    print(f"AGOR snapshot: {csvs[-1].get('name')}")
    return list(csv.DictReader(io.StringIO(blob)))


def harvest_grounds():
    grounds, exemptions, scanned = {}, {}, 0
    for f, t in SCAN_DAYS:
        url = OCDS.format(f=f, t=t)
        for _ in range(3):
            d = fetch(url)
            rs = d.get("releases", [])
            scanned += len(rs)
            for r in rs:
                tn = r.get("tender", {})
                if tn.get("limitedTenderReasonCode"):
                    grounds[tn["limitedTenderReasonCode"]] = tn.get("limitedTenderReason", "")
                if tn.get("exemptionCode"):
                    exemptions[tn["exemptionCode"]] = tn.get("exemption", "")
            nxt = (d.get("links") or {}).get("next")
            if not nxt:
                break
            url = nxt
            time.sleep(0.35)
        time.sleep(0.35)
    return grounds, exemptions, scanned


def main():
    rows = latest_agor_rows()
    primary = [r for r in rows if (r.get("Classification") or "").startswith("A.")]
    portfolios = sorted({r["Portfolio"].strip() for r in rows if r.get("Portfolio", "").strip()})
    by_title = {r["Title"].strip(): r for r in rows}
    alias_by_title = collections.defaultdict(list)
    for austender_name, agor_title in ALIASES.items():
        if agor_title in by_title:
            alias_by_title[agor_title].append(austender_name)
        else:
            print(f"  WARNING alias target not in AGOR: {agor_title}")

    with open("reference/agencies.yml", "w") as f:
        f.write("# GENERATED by scripts/build-reference-data.py — do not hand-edit.\n"
                "# Source: Australian Government Organisations Register (data.gov.au, CC BY 3.0 AU).\n"
                "# Seeded idempotently into the KG on world load (identity-MERGE on name).\n"
                "#\n"
                "# The agency spine: contracts carry an agency NAME string; these nodes give that\n"
                "# string a portfolio, an ABN, a body type and a staffing/appropriations context, so\n"
                "# 'what did this portfolio sign' is a traversal rather than a hand-kept list.\n"
                "# austenderAliases carries the spellings AusTender publishes that differ from the\n"
                "# legal title — reviewable, because the drift cannot be derived by a rule.\n\n")
        for p in portfolios:
            f.write(f"- type: Portfolio\n  data: {{ name: {yq(p)} }}\n")
        f.write("\n")
        for r in primary:
            title = r["Title"].strip()
            data = [f"name: {yq(title)}"]
            for key, prop in (("ABN", "abn"), ("Type of Body", "bodyType"),
                              ("GFS Sector Classification", "gfsSector"),
                              ("Average Staffing Level (ASL)", "staffingLevel"),
                              ("Total Appropriations ($000)", "appropriationsThousands"),
                              ("Website Address", "website")):
                v = (r.get(key) or "").strip()
                if v:
                    data.append(f"{prop}: {yq(v)}")
            aliases = alias_by_title.get(title, [])
            if aliases:
                data.append("austenderAliases: [" + ", ".join(yq(a) for a in aliases) + "]")
            f.write(f"- type: Agency\n  data: {{ {', '.join(data)} }}\n")
            port = (r.get("Portfolio") or "").strip()
            if port:
                f.write(f"  relations:\n    - predicate: IN_PORTFOLIO\n      to: {{ type: Portfolio, name: {yq(port)} }}\n")
    print(f"reference/agencies.yml: {len(portfolios)} portfolios, {len(primary)} agencies")

    grounds, exemptions, scanned = harvest_grounds()
    with open("reference/procurement-grounds.yml", "w") as f:
        f.write("# GENERATED by scripts/build-reference-data.py — do not hand-edit.\n"
                f"# HARVESTED from {scanned} live AusTender releases: every distinct code the register\n"
                "# actually published, with ITS OWN verbatim text. Not transcribed from the\n"
                "# Commonwealth Procurement Rules — a paraphrased rule presented as a citation is the\n"
                "# failure this realm exists to avoid.\n"
                "#\n"
                "# kind=limited-tender: the ground an agency stated for going to a single supplier.\n"
                "# kind=exemption: an Appendix A exemption from the CPR division-2 rules.\n"
                "# Both are RECORDED REASONS, never assessments of them.\n\n")
        for code, text in sorted(grounds.items()):
            f.write(f"- type: ProcurementGround\n  data: {{ code: {yq(code)}, kind: \"limited-tender\", text: {yq(text)} }}\n")
        for code, text in sorted(exemptions.items()):
            f.write(f"- type: ProcurementGround\n  data: {{ code: {yq(code)}, kind: \"exemption\", text: {yq(text)} }}\n")
    print(f"reference/procurement-grounds.yml: {len(grounds)} grounds + {len(exemptions)} exemptions "
          f"(from {scanned} releases)")


if __name__ == "__main__":
    main()
