#!/usr/bin/env python3
"""Regenerate reference/electorates.yml — the 150 federal divisions with their sitting member,
party and two-party-preferred margin. Do not hand-edit the output.

Source: the AEC's OFFICIAL final results for the 2025 federal election (results.aec.gov.au),
not Wikipedia — the AEC is the authority, publishes machine-readable CSV, and states its own
generation timestamp inside the file.

  HouseTppByDivisionDownload  -> two-party-preferred percentages per division
  HouseMembersElectedDownload -> the member elected in each division

MARGIN is derived as |TPP% - 50| for the winning side of the two-party count — the standard
definition, and the reason a "marginal seat" is conventionally under 6%. Divisions won by
independents or minor parties still HAVE a two-party-preferred count (it is computed between
ALP and the Coalition regardless), so `heldBy` comes from the members file and can differ from
the party leading the TPP. Both are published so no surface has to guess.

Only 150 rows, and they change at an election — reference data that ships with the pack.

Run from the realm root:  python3 scripts/build-electorate-reference.py
"""
import csv
import io
import urllib.request

EVENT = "31496"  # 2025 federal election. Update at the next election and re-run.
BASE = f"https://results.aec.gov.au/{EVENT}/Website/Downloads/"
TPP = BASE + f"HouseTppByDivisionDownload-{EVENT}.csv"
MEMBERS = BASE + f"HouseMembersElectedDownload-{EVENT}.csv"
UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}


def fetch_csv(url):
    raw = urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120).read().decode("utf-8-sig")
    lines = raw.splitlines()
    # The AEC prefixes each file with a provenance banner line before the real header.
    start = next(i for i, l in enumerate(lines) if l.startswith("DivisionNm") or l.startswith("DivisionID"))
    return list(csv.DictReader(io.StringIO("\n".join(lines[start:])))), lines[0]


def yq(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    tpp, tpp_banner = fetch_csv(TPP)
    members, _ = fetch_csv(MEMBERS)
    by_div = {m["DivisionNm"].strip(): m for m in members}

    rows = []
    for t in tpp:
        div = t["DivisionNm"].strip()
        alp = float(t["Australian Labor Party Percentage"])
        lnp = float(t["Liberal/National Coalition Percentage"])
        lead, leadPct = ("ALP", alp) if alp >= lnp else ("LNP", lnp)
        margin = round(abs(leadPct - 50.0), 2)
        m = by_div.get(div, {})
        rows.append({
            "division": div,
            "state": t["StateAb"].strip(),
            "tppLeader": lead,
            "tppLeaderPct": round(leadPct, 2),
            "marginPct": margin,
            "marginBand": "very marginal (<3%)" if margin < 3 else
                          "marginal (3-6%)" if margin < 6 else
                          "fairly safe (6-10%)" if margin < 10 else "safe (10%+)",
            "swing": t.get("Swing", "").strip(),
            "member": (m.get("GivenNm", "") + " " + m.get("Surname", "")).strip(),
            "heldByParty": m.get("PartyNm", "").strip(),
            "heldByAbbrev": m.get("PartyAb", "").strip(),
        })

    with open("reference/electorates.yml", "w") as f:
        f.write("# GENERATED by scripts/build-electorate-reference.py — do not hand-edit.\n")
        f.write("# Source: AEC official final results, 2025 federal election (results.aec.gov.au).\n")
        f.write(f"# {tpp_banner.strip()[:150]}\n")
        f.write("#\n")
        f.write("# 150 divisions with the sitting member, the party holding the seat, and the\n")
        f.write("# two-party-preferred margin (|TPP% - 50| for the leading side). `heldByParty` can\n")
        f.write("# differ from `tppLeader` where an independent or minor party won the seat — the TPP\n")
        f.write("# count is computed between ALP and the Coalition regardless, so both are published\n")
        f.write("# and no surface has to guess which one it means.\n")
        f.write("#\n")
        f.write("# THESE ARE ELECTION FACTS. Joining them to grant DELIVERY locations answers a fair\n")
        f.write("# public question about where money lands; it establishes nothing about why, and any\n")
        f.write("# surface using it must say so.\n\n")
        for r in rows:
            data = ", ".join(f"{k}: {yq(v)}" if isinstance(v, str) else f"{k}: {v}" for k, v in r.items())
            f.write(f"- type: Electorate\n  data: {{ {data} }}\n")

    bands = {}
    for r in rows:
        bands[r["marginBand"]] = bands.get(r["marginBand"], 0) + 1
    print(f"reference/electorates.yml: {len(rows)} divisions")
    for b, n in sorted(bands.items()):
        print(f"  {b}: {n}")


if __name__ == "__main__":
    main()
